[package]
name = "is_positive"
version = "0.1.338"
edition = "2021"
description = "A simple Rust library to check if any non-ZST is positive"
license = "MIT"
repository = "https://github.com/LilDojd/is_positive"
